spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/invest_sns?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlqjs

# return "redirect:/"; 로 바꿨을때, 세션ID가 URL에 나왔던거 없애줌 
server:
  servlet:
    session: 
      tracking-modes: cookie

logging:
  level:
    root: info
